# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-24 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=200)),
                ('categoryId', models.BigIntegerField()),
                ('rank', models.BigIntegerField()),
            ],
        ),
    ]
