# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('name3', models.CharField(max_length=200)),
                ('name4', models.CharField(max_length=200)),
                ('name5', models.CharField(max_length=200)),
                ('name6', models.CharField(max_length=200)),
                ('id1', models.BigIntegerField()),
                ('id2', models.BigIntegerField()),
                ('id3', models.BigIntegerField()),
                ('id4', models.BigIntegerField()),
                ('id5', models.BigIntegerField()),
                ('id6', models.BigIntegerField()),
                ('gender1', models.CharField(max_length=1)),
                ('gender2', models.CharField(max_length=1)),
                ('gender3', models.CharField(max_length=1)),
                ('gender4', models.CharField(max_length=1)),
                ('gender5', models.CharField(max_length=1)),
                ('gender6', models.CharField(max_length=1)),
                ('category1', models.BigIntegerField()),
                ('category2', models.BigIntegerField()),
                ('category3', models.BigIntegerField()),
                ('category4', models.BigIntegerField()),
                ('category5', models.BigIntegerField()),
                ('category6', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=1)),
                ('young_counter', models.BigIntegerField()),
                ('middle_counter', models.BigIntegerField()),
                ('old_counter', models.BigIntegerField()),
                ('name1', models.CharField(max_length=200)),
                ('name2', models.CharField(max_length=200)),
                ('name3', models.CharField(max_length=200)),
                ('name4', models.CharField(max_length=200)),
                ('name5', models.CharField(max_length=200)),
                ('name6', models.CharField(max_length=200)),
                ('name7', models.CharField(max_length=200)),
                ('name8', models.CharField(max_length=200)),
                ('id1', models.BigIntegerField()),
                ('id2', models.BigIntegerField()),
                ('id3', models.BigIntegerField()),
                ('id4', models.BigIntegerField()),
                ('id5', models.BigIntegerField()),
                ('id6', models.BigIntegerField()),
                ('id7', models.BigIntegerField()),
                ('id8', models.BigIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='camper',
            old_name='categoryId',
            new_name='category_id',
        ),
    ]
