# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camper', '0002_auto_20170925_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camper',
            name='age',
            field=models.BigIntegerField(choices=[(13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18')], default=13),
        ),
    ]
