# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camper', '0004_auto_20170925_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dorm',
            old_name='id1',
            new_name='middle_count',
        ),
        migrations.RenameField(
            model_name='dorm',
            old_name='id2',
            new_name='old_count',
        ),
        migrations.RenameField(
            model_name='dorm',
            old_name='id3',
            new_name='young_count',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='id4',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='id5',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='id6',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='id7',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='id8',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='middle_counter',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='name6',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='name7',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='name8',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='old_counter',
        ),
        migrations.RemoveField(
            model_name='dorm',
            name='young_counter',
        ),
        migrations.AddField(
            model_name='dorm',
            name='camper',
            field=models.ManyToManyField(blank=True, null=True, to='Camper.Camper'),
        ),
        migrations.AddField(
            model_name='dorm',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
