# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camper', '0005_auto_20170925_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='middle_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='old_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dorm',
            name='young_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
