# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camper', '0006_auto_20170925_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='band',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='band',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='band',
            name='category4',
        ),
        migrations.RemoveField(
            model_name='band',
            name='category5',
        ),
        migrations.RemoveField(
            model_name='band',
            name='category6',
        ),
        migrations.RemoveField(
            model_name='band',
            name='gender1',
        ),
        migrations.RemoveField(
            model_name='band',
            name='gender2',
        ),
        migrations.RemoveField(
            model_name='band',
            name='gender3',
        ),
        migrations.RemoveField(
            model_name='band',
            name='gender4',
        ),
        migrations.RemoveField(
            model_name='band',
            name='gender5',
        ),
        migrations.RemoveField(
            model_name='band',
            name='gender6',
        ),
        migrations.RemoveField(
            model_name='band',
            name='id1',
        ),
        migrations.RemoveField(
            model_name='band',
            name='id2',
        ),
        migrations.RemoveField(
            model_name='band',
            name='id3',
        ),
        migrations.RemoveField(
            model_name='band',
            name='id4',
        ),
        migrations.RemoveField(
            model_name='band',
            name='id5',
        ),
        migrations.RemoveField(
            model_name='band',
            name='id6',
        ),
        migrations.RemoveField(
            model_name='band',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='band',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='band',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='band',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='band',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='band',
            name='name6',
        ),
        migrations.AddField(
            model_name='band',
            name='boys_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='band',
            name='camper',
            field=models.ManyToManyField(blank=True, null=True, to='Camper.Camper'),
        ),
        migrations.AddField(
            model_name='band',
            name='girls_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
