# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camper', '0007_auto_20170925_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
